settings:
  name: "Product Name"
  noindex: true
  
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
  - title: Legal notices
    url: /legal-notices.html
