settings:
  name: System Manager Classic
  noindex: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: System Manager Classic docs
      url: /index.html
    - title: Provision NAS storage
      entries:
      - section: nfs-config
      - section: nfs-config-esxi
      - section: nas-multiprotocol-config
      - section: smb-config
    - title: Provision SAN storage
      entries:
      - section: fc-config-esxi
      - section: fc-config-rhel
      - section: fc-config-windows
      - section: iscsi-config-esxi
      - section: iscsi-config-rhel
      - section: iscsi-config-windows
    - title: Data protection and disaster recovery
      entries:
      - section: peering
      - section: volume-disaster-recovery
      - section: volume-disaster-prep
      - section: volume-backup-snapvault
      - section: volume-restore-snapvault
    - title: Cluster administration
      entries:
      - section: expansion
      - section: volume-move
      - section: snmp-config
    - title: Cluster management using System Manager 9.6 and 9.7
      entries:
      - section: online-help-96-97
    - title: Network management for ONTAP 9.7 and earlier
      entries:
      - section: networking-failover
      - section: networking-bd
      - section: networking
    - title: ONTAP docs
      url: https://docs.netapp.com/us-en/ontap/
    - title: Legal notices
      url: /legal-notices.html


product-family: 
  name: ONTAP
  repo: ontap-family
  