---
permalink: online-help-96-97/concept_snapshot_policies.html
sidebar: sidebar
keywords: snapshot, manager, system, create, manage, policy, storage, online, help
summary: "You can use System Manager to create and manage Snapshot policies in your storage system."
---
= Manage Snapshot policies with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to create and manage Snapshot policies in your storage system.

== About Snapshot policies

When applied to a volume, a Snapshot policy specifies a schedule or schedules according to which Snapshot copies are created and specifies the maximum number of Snapshot copies that each schedule can create. A Snapshot policy can include up to five schedules.

For vault relationships, the SnapMirror Label attribute is used to select Snapshot copies on the source volumes. Only Snapshot copies with the labels configured in the vault policy rules are replicated in backup vault operations. The Snapshot policy assigned to the source volume must include the SnapMirror Label attribute.

== Create Snapshot policies

You can create a Snapshot policy in System Manager to specify the maximum number of Snapshot copies that can be automatically created and the frequency of creating them.

.Steps

. Click *Protection* > *Snapshot Policies*.
. Click *Create*.
. In the *Create Snapshot Policy* dialog box, specify the policy name.
. Click *Add*, and then specify the schedule name, the maximum number of Snapshot copies that you want to retain, and the SnapMirror label name.
+
The maximum number of Snapshot copies that can be retained by the specified schedules must not exceed 254.

. Click *OK*, and then click *Create*.
//2021-12-07, created by Mairead sm-classic-rework

== Edit Snapshot policies

You can modify the details of an existing Snapshot policy, such as the schedule name, SnapMirror label, or the maximum number of Snapshot copies that are created, by using the Edit Snapshot Policy dialog box in System Manager.

.Steps

. Click *Protection* > *Snapshot Policies*.
. In the *Snapshot Policies* window, select the Snapshot policy that you want to modify and click *Edit*.
. In the *Edit Snapshot Policy* dialog box, select the schedule that you want to modify and click *Edit*.
. Click *OK*.
. Verify the changes you made to the selected Snapshot policy in the *Edit Snapshot Policy* dialog box and click *Save*.
//2021-12-07, created by Mairead sm-classic-rework

== Delete Snapshot policies

You can use System Manager to delete Snapshot policies. If you delete a Snapshot policy that is being used by one or more volumes, Snapshot copies of the volume or volumes are no longer created according to the deleted policy.

.Before you begin

You must have dissociated the Snapshot policy from each volume that uses it.

.Steps

. Click *Protection* > *Snapshot Policies*.
. Select the Snapshot policy and click *Delete*.
. Select the confirmation check box, and then click *Delete*.

== Snapshot Policies window

You can use the Snapshot Policies window to manage Snapshot policy tasks, such as adding, editing, and deleting Snapshot policies.

=== Command buttons

* *Create*
+
Opens the Create Snapshot Policy dialog box, which enables you to add backup schedules and specify the maximum number of Snapshot copies to be retained in a policy.

* *Edit*
+
Opens the Edit Snapshot Policy dialog box, which enables you to modify the frequency at which Snapshot copies should be created and the maximum number of Snapshot copies to be retained.

* *Delete*
+
Opens the Delete dialog box, which enables you to delete the selected Snapshot policy.

* *View as*
+
Enables you to view the Snapshot policies either as a list or as a tree.

* *Status*
+
Opens the menu, which you can use to either enable or disable the selected Snapshot policy.

* *Refresh*
+
Updates the information in the window.

=== Snapshot policy list

* *Policy/Schedule Name*
+
Specifies the name of the Snapshot policy and the schedules in the policy.

* *Storage Virtual Machine*
+
Specifies the name of the storage virtual machine (SVM) to which the Snapshot copies belong.

* *Status*
+
Specifies the status of the Snapshot policy, which can be Enabled or Disabled.

* *Maximum Snapshots to be retained*
+
Specifies the maximum number of Snapshot copies to be retained.

* *SnapMirror Label*
+
Specifies the name of the SnapMirror label attribute of the Snapshot copy generated by the backup schedule.

//2021-12-09, created by Mairead sm-classic-rework
//2021-12-09, edited by Aoife, sm-classic rework
