---
permalink: online-help-96-97/concept_nis_services.html
sidebar: sidebar
keywords: online, help, system, manager, nis, services, add, edit, manage, network, information, service, domain, svm, modify, command
summary: "You can use System Manager to add, edit, and manage Network Information Service (NIS) domains."
---
= Manage NIS services with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to add, edit, and manage Network Information Service (NIS) domains.

== Add NIS domains

You can maintain host information centrally by using NIS. You can use System Manager to add the NIS domain name of your storage system. Only one NIS domain can be active on a storage virtual machine (SVM) at any given time.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Services* pane, click *NIS*.
. Click *Create*.
. Type the NIS domain name, and then add one or more NIS servers.
. Click *Create*.

== Edit NIS domains

You can use System Manager to modify NIS domains based on the requirement for storage virtual machine (SVM) authentication and authorization.

.Steps

. Click *Storage* > *SVMs*.
. Select the SVM, and then click *SVM Settings*.
. In the *Services* pane, click *NIS*.
. Select the NIS domain, and then click *Edit*.
. Make the required changes, and then click *Edit*.

== NIS window

The NIS window enables you to view the current NIS settings for your storage system.

=== Command buttons

* *Create*
+
Opens the Create NIS Domain dialog box, which enables you to create NIS domains.

* *Edit*
+
Opens the Edit NIS Domain dialog box, which enables you to add, delete, or modify NIS servers.

* *Delete*
+
Deletes the selected NIS domain.

* *Refresh*
+
Updates the information in the window.

*Related information*

https://docs.netapp.com/us-en/ontap/nfs-config/index.html[NFS configuration^]

// 2021-12-21, Created by Aoife, sm-classic rework
