---
permalink: online-help-96-97/task_aborting_vault_relationships.html
sidebar: sidebar
keywords: abort, snapshot, copy, transfer, online, help, system, manager
summary: "You can use System Manager to abort or stop a data transfer that is currently in progress."
---
= Abort a Snapshot copy transfer with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to abort or stop a data transfer that is currently in progress.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the relationship for which you want to stop the data transfer, and click *Operations* > *Abort*.
. Select the *Yes, I want to abort the transfer* check box to confirm the operation.
. *Optional:* Select the *Keep any partially transferred data* check box to retain the data that is already transferred to the destination volume.
. Click *Abort*.

.Results

The transfer status is displayed as "`Aborting`" until the operation is complete and displayed as "`Idle`" after the operation is complete.

*Related information*

xref:reference_protection_window.adoc[Protection window]
