---
permalink: online-help-96-97/task_editing_vault_relationships.html
sidebar: sidebar
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule
summary: "You can use System Manager to edit a vault relationship either by selecting an existing policy or schedule in the cluster, or by creating a new policy or schedule. However, you cannot edit the parameters of an existing policy or schedule."
---
= Manage vault relationships with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to update, resume, quiesce, initialize and delete vault relationships in addition to creating vault relationships from a destination SVM.

== Edit relationships

You can use System Manager to edit a vault relationship either by selecting an existing policy or schedule in the cluster, or by creating a new policy or schedule. However, you cannot edit the parameters of an existing policy or schedule.

.Before you begin

The source and destination clusters must be in a healthy peer relationship.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the vault relationship for which you want to modify the policy or schedule, and then click *Edit*.
. In the *Edit Relationship* dialog box, select the appropriate action:
+
[options="header"]
|===
| If you want to...| Do the following...
a|
Select an existing policy
a|
Click *Browse*, and then select an existing policy.    You can select a policy that has the maximum number of matching labels with the Snapshot policy that is attached to the source volume.
a|
Create a new policy
a|

 .. Click *Create Policy*.
 .. Specify a name for the policy.
 .. Set the priority for scheduled transfers.
+
Low indicates that the transfer has the least priority and is usually scheduled after normal priority transfers. By default, the priority is set to Normal.

 .. Select the *Enable Network Compression* check box to compress the data that is being transferred.
 .. Specify a SnapMirror label and destination retention count for the vault policy.
+
You must ensure that a Snapshot copy with the same label is created on the source volume for the new SnapMirror label to be effective.

 .. Click *Create*.

|===

. Specify a schedule for the relationship:
+
[options="header"]
|===
| If...| Do the following...
a|
You want to assign an existing schedule
a|
Select an existing schedule from the list.
a|
You want to create a new schedule
a|

 .. Click *Create Schedule*.
 .. Specify a name for the schedule.
 .. Select one of the following options:
  *** *Basic*
+
You can select this option to specify only the day of the week, time, and the transfer interval.

  *** *Advanced*
+
You can select this option to specify a cron-style schedule.
 .. Click *Create*.

a|
You do not want to assign a schedule
a|
Select *None*.
|===

. Click *OK*.

*Related information*

xref:reference_protection_window.adoc[Protection window]

== Initialize relationships

You can use System Manager to initialize a vault relationship if you have not already initialized it while creating the relationship. A baseline transfer of data is initiated from the source FlexVol volume to the destination FlexVol volume.

.Before you begin

The source and destination clusters must be in a healthy peer relationship.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the relationship you want to initialize, and click *Operations* > *Initialize*.
. In the *Initialize* window, click *Initialize*.

.Results

A Snapshot copy is created and transferred to the destination.

This Snapshot copy is used as a baseline for subsequent incremental Snapshot copies.

*Related information*

xref:reference_protection_window.adoc[Protection window]

== Create relationships from a destination SVM

You can use System Manager to create a vault relationship from the destination storage virtual machine (SVM), and to assign a vault policy to create a backup vault. In the event of data loss or corruption on a system, backed-up data can be restored from the backup vault destination.

.Before you begin

* The source cluster must be running ONTAP 8.2.2 or later.
* SnapVault license or SnapMirror license must be enabled on both the source cluster and the destination cluster.
+
[NOTE]
====
For some platforms, it is not mandatory for the source cluster to have the SnapVault license or the SnapMirror license enabled if the destination cluster has the SnapVault license or the SnapMirror license, and DPO license enabled.
====

* The source cluster and destination cluster must be in a healthy peer relationship.
* The destination SVM must have space available.
* The source aggregate and the destination aggregate must be 64-bit aggregates.
* A source volume of type read/write (rw) must exist.
* A vault (XDP) policy must exist.
+
If a vault policy does not exist, you must create a vault policy or accept the default vault policy (XDPDefault) that is automatically assigned.

* FlexVol volumes must be online and read/write.
* The SnapLock aggregate type must be the same.
* If you are connecting from a cluster running ONTAP 9.2 or earlier to a remote cluster on which SAML authentication is enabled, password-based authentication must be enabled on the remote cluster.

.About this task

* System Manager does not support a cascade relationship.
+
For example, a destination volume in a relationship cannot be the source volume in another relationship.

* You cannot create a vault relationship between a sync-source SVM and a sync-destination SVM in a MetroCluster configuration.
* You can create a vault relationship between sync-source SVMs in a MetroCluster configuration.
* You can create a vault relationship from a volume on a sync-source SVM to a volume on a data-serving SVM.
* You can create a vault relationship from a volume on a data-serving SVM to a data protection (DP) volume on a sync-source SVM.
* You can create a vault relationship only between a non-SnapLock (primary) volume and a SnapLock destination (secondary) volume.
* A maximum of 25 volumes can be protected in one selection.

.Steps

. Click *Protection* > *Volume Relationships*.
. In the *Relationships* window, click *Create*.
. In the *Browse SVM* dialog box, select an SVM for the destination volume.
. In the *Create Protection Relationship* dialog box, select *Vault* from the *Relationship Type* drop-down list.
. Specify the cluster, the SVM, and the source volume.
+
If the specified cluster is running a version of ONTAP software earlier than ONTAP 9.3, then only peered SVMs are listed. If the specified cluster is running ONTAP 9.3 or later, peered SVMs and permitted SVMs are listed.

. Enter a volume name suffix.
+
The volume name suffix is appended to the source volume names to generate the destination volume names.

. If you are creating a SnapLock volume, specify the default retention period.
+
The default retention period can be set to any value between 1 day through 70 years or Infinite.

. *Optional:* Click *Browse*, and then change the vault policy.
. Select a schedule for the relationship from the list of existing schedules.
. *Optional:* Select *Initialize Relationship* to initialize the vault relationship.
. Enable SnapLock aggregates, and then select a SnapLock Compliance aggregate or a SnapLock Enterprise aggregate.
. Enable FabricPool-enabled aggregates, and then select an appropriate tiering policy.
. Click *Validate* to verify whether the selected volumes have matching labels.
. Click *Create*.

.Results

If you chose to create a destination volume, a volume of type _dp_ is created with the following default settings:

* Autogrow is enabled.
* Deduplication is enabled or disabled according to the user preference or the source volume deduplication setting.
* Compression is disabled.
* The language attribute is set to match the language attribute of the source volume.

A vault relationship is created between the destination volume and the source volume. The base Snapshot copy is transferred to the destination volume if you have opted to initialize the relationship.

== Update relationships

You can use System Manager to manually initiate an unscheduled incremental update. You might require a manual update to prevent data loss due to an upcoming power outage, scheduled maintenance, or data migration.

.Before you begin

The vault relationship must be initialized.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the relationship for which you want to update the data, and click *Operations* > *Update*.
. Choose one of the following options:
 ** Select *As Per Policy* to perform an incremental transfer from the recent common Snapshot copy between the source and destination volumes.
 ** Select *Select Snapshot copy* and specify the Snapshot copy that you want to transfer.
. *Optional:* Select *Limit transfer bandwidth to* to limit the network bandwidth that is used for transfers and specify the maximum transfer speed.
. Click *Update*.
. Verify the transfer status in the *Details* tab.

== Delete relationships

You can use System Manager to end a vault relationship between a source and destination volume, and release the Snapshot copies from the source.

.About this task

Releasing the relationship permanently removes the base Snapshot copies used by the vault relationship on the source volume. To re-create the vault relationship, you must run the resynchronization operation from the source volume by using the command-line interface (CLI).

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the volume for which you want to delete the vault relationship, and click *Delete*.
. Select the confirmation check box, and then click *Delete*.
+
You can also select the release base Snapshot copies check box to delete the base Snapshot copies used by the vault relationship on the source volume.
+
If the relationship is not released, then you must use the CLI to run the release operation on the source cluster to delete the base Snapshot copies that were created for the vault relationship from the source volume.

== Resume relationships

You can resume a quiesced vault relationship by using System Manager. When you resume the relationship, normal data transfer to the destination FlexVol volume is resumed and all vault activities are restarted.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the relationship for which you want to resume the data transfer, and click *Operations* > *Resume*.
. In the *Resume* window, click *Resume*.

.Results

Normal data transfers are resumed. If there is a scheduled transfer for the relationship, the transfer is started from the next schedule.

== Quiesce relationships

You can use System Manager to disable data transfers to the destination FlexVol volume by quiescing the vault relationship.

.Steps

. Click *Protection* > *Volume Relationships*.
. Select the relationship for which you want to stop the scheduled data transfers, and click *Operations* > *Quiesce*.
. In the *Quiesce* window, click *Quiesce*.

.Results

If there is no transfer in progress, the transfer status is displayed as Quiesced. If a transfer is in progress, the transfer is not affected, and the transfer status is displayed as Quiescing until the transfer is complete.

*Related information*

xref:reference_protection_window.adoc[Protection window]

// 2022-05-27, sm-classic rework
