---
permalink: online-help-96-97/task_setting_up_network.html
sidebar: sidebar
keywords: set, up, network, cluster, node, service, processor, dns, ntp, online, help
summary: "By setting up a network, you can manage your cluster, nodes, and Service Processors. You can also set up DNS and NTP details by using the network window."
---
= Set up a network with System Manager - ONTAP 9.7 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager classic (available in ONTAP 9.7 and earlier) to manage your cluster, nodes, and Service Processors by setting up a network. You can also set up DNS and NTP details by using the network window.

.Before you begin

You must have set up the cluster.

.About this task

* Only those nodes that are up and running are listed for cluster creation.
+
You can create LIFs for those nodes.

* You can disable IP address range and enter individual IP addresses for cluster management, node management, and Service Processor management networks.

== Set up a network when an IP address range is enabled

You can set up a network by enabling an IP address range. The IP address range enables you to enter IP addresses that are in the same netmask range or in the different netmask range.

.Steps

. Enter a range of IP addresses in the *IP Address Range* field, and then click *Apply*.
+
[options="header"]
|===
| Option| Description
a|
You have a range of IP addresses in the same netmask
a|
Enter the IP address range, and then click *Apply*.

IP addresses are applied to cluster management, node management, and Service Processor management networks sequentially.
a|
You have a range of IP addresses in different netmasks
a|
Enter each IP address range on a separate line, and then click *Apply*.

The first IP address applied to cluster management and other IP addresses are applied to node management and Service Processor management networks sequentially.

|===
+
[NOTE]
====
After entering the IP address range for cluster management, node management, and Service Processor management, you must not manually modify the IP address values in these fields. You must ensure that all the IP addresses are IPv4 addresses.
====

. Enter the netmask and gateway details.
. Select the port for cluster management in the *Port* field.
. If the *Port* field in the node management is not populated with *e0M*, enter the port details.
+
[NOTE]
====
By default, the Port field displays e0M.
====

. For Service Processor management, if you are overriding the default values, ensure that you have entered the mandatory gateway details.
. If you have enabled the *DNS Details* field, enter the DNS server details.
. If you have enabled the *NTP Details* field, enter the NTP server details.
+
[NOTE]
====
Providing alternative NTP server details is optional.
====

. Click *Submit*.

=== What to do next

Enter event notifications in the Support page to continue with the cluster setup.

== Set up a network when an IP address range is disabled

You can set up a network by disabling an IP address range and entering individual IP addresses for cluster management, node management, and service provider networks.

.About this task

In the Networks page, if the *IP Address Range* is disabled, enter individual IP addresses for cluster management, node management, and service processor networks.

.Steps

. Enter the cluster management IP address in the *Cluster Management IP Address* field.
. Enter the netmask details for cluster management.
. *Optional:* Enter the gateway details for cluster management.
. Select the port for cluster management in the *Port* field.
. If you want to provide netmask and gateway details to manage your nodes, clear the *Retain Netmask and Gateway configuration of the Cluster Management* check box, and then enter the netmask and gateway details.
. Enter the node management IP addresses in the *Node Management* field.
. If the *Port* field in the node management is not populated with *e0M*, enter the port details.
+
[NOTE]
====
By default, the Port field displays e0M.
====

. Enter the Service Processor management netmask and gateway details.
. Enter the Service Processor IP management addresses in the *Service Processor Management* field.
. If you have enabled the *DNS Details* field, enter the DNS server details.
. If you have enabled the *NTP Details* field, enter the NTP server details.
+
[NOTE]
====
Providing alternative NTP server details is optional.
====

. Click *Submit*.

=== What to do next

Enter event notifications in the Support page to continue with the cluster setup.

*Related information*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/What_is_a_Service_Processor_and_how_do_I_use_it%3F[What is a Service Processor and how do I use it?]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_and_troubleshoot_NTP_on_clustered_Data_ONTAP_8.2_and_later_using_CLI[How to configure and troubleshoot NTP on clustered Data ONTAP 8.2 and later using CLI]

https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]

xref:reference_network_window.adoc[Network window]

xref:reference_configuration_updates_window.adoc[Configuration Updates window]

xref:reference_date_time_window.adoc[Date and Time window]

xref:reference_service_processors_window.adoc[Service Processors window]

// sm-classic rework, 2022-04-12
