---
permalink: smb-config/task_deciding_where_to_provision_new_volume.html
sidebar: sidebar
keywords: create, cifs, volume, place, exist, storage, virtual, machine, svm, configuration, require, decision, workflow, decide where to provision the new volume
summary: "Before you create a new CIFS volume, you must decide whether to place it in an existing storage virtual machine (SVM), and, if so, how much configuration the SVM requires. This decision determines your workflow."
---
= Decide where to provision the new volume
:icons: font
:imagesdir: ../media/

[.lead]
Before you create a new CIFS volume, you must decide whether to place it in an existing storage virtual machine (SVM), and, if so, how much configuration the SVM requires. This decision determines your workflow.

== Procedure

* If you want to provision a volume on a new SVM, create a new CIFS-enabled SVM.
+
link:task_creating_protocol_enabled_svm.html[Creating a new CIFS-enabled SVM]
+
You must choose this option if CIFS is not enabled on an existing SVM.

* If you want to provision a volume on an existing SVM on which CIFS is enabled but not configured, configure CIFS/SMB access on the existing SVM.
+
link:task_configuring_access_to_existing_svm.html[Configuring CIFS/SMB access on an existing SVM]
+
You should choose this option if you used the procedure to create the SVM for SAN access.

* If you want to provision a volume on an existing SVM that is fully configured for CIFS access, add a CIFS volume to the CIFS-enabled SVM.
+
link:concept_adding_protocol_volume_to_protocol_enabled_svm.html[Adding a CIFS volume to a CIFS-enabled SVM]

// BURT 1448684, 31 JAN 2022
