---
permalink: fc-config-windows/index.html
sidebar: sidebar
keywords: describe, fc, service, storage virtual machine, svm, provision, lun, hba, windows, host
summary: "You can quickly set up the FC service on a storage virtual machine, provision a LUN, and make the LUN available using an FC HBA on a Windows host computer."
---
= FC configuration for Windows overview
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
You can quickly set up the FC service on a storage virtual machine (SVM), provision a LUN, and make the LUN available using an FC HBA on a Windows host computer with the ONTAP System Manager classic interface (ONTAP 9.7 and earlier).

Use this procedure to set up FC service on an SVM if:

* You are using traditional FC HBAs and switches.

This procedure does not covers situations where:

* You have at least two FC target ports available on each node in the cluster.
Onboard FC and UTA2 (also called `CNA`) ports, as well as some adapters are configurable. Configuring those ports is done in the ONTAP CLI and is not covered in this procedure.
* You are not configuring FC SAN boot.
* You are not using virtual Fibre Channel (VFC) with Hyper-V or ESX guests.

== Other ways to do this in ONTAP

|===

h| To perform these tasks with... h| Refer to...
| The redesigned System Manager (available with ONTAP 9.7 and later) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_windows.html[Provision SAN storage for Windows servers^]
| The ONTAP command line interface (CLI) | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html[LUN setup workflow with the CLI^]
|===

.Additional Resources
* https://docs.netapp.com/us-en/ontap-sanhost/index.html[NetApp Documentation: Host Utilities^]

// BURT 1416427, 17 DEC 2021
// BURT 1448684, 31 JAN 2022
