---
permalink: volume-disaster-prep/index.html
sidebar: sidebar
keywords: content, protect, source, volume, peer, ontap, cluster, preparation, disaster, recovery, configure, monitor, snapmirror, relationship, background, task, volume disaster recovery preparation overview
summary: "You can quickly protect a source volume on a peered ONTAP cluster in preparation for disaster recovery. You should use this content if you want to configure and monitor SnapMirror relationships between peered clusters for volume disaster recovery and do not need a lot of conceptual background for the tasks."
---
= Volume disaster recovery preparation overview
:icons: font
:imagesdir: ../media/

[.lead]
You can quickly protect a source volume on a peered ONTAP cluster in preparation for disaster recovery. You should use this procedure if you want to configure and monitor SnapMirror relationships between peered clusters for volume disaster recovery and do not need a lot of conceptual background for the tasks.

SnapMirror provides scheduled asynchronous, block-level data protection. SnapMirror replicates Snapshot copies and can replicate NAS or SAN volumes on which deduplication, data compression, or both are run, including volumes containing qtrees and LUNs. SnapMirror configuration information is stored in a database that ONTAP replicates to all the nodes in the cluster.

Use this procedure if you want to create SnapMirror relationships for volume-level disaster recovery in the following way:

* You are working with clusters running ONTAP 9.
* You are a cluster administrator.
* You have configured the cluster peer relationship and the SVM peer relationship.
+
link:../peering/index.html[Cluster and SVM peering configuration]

* You have enabled the SnapMirror license on both the source and the destination clusters.
* You want to use default policies and schedules, and not create custom policies.
* You want to use best practices, not explore every available option (ONTAP 9.7 and earlier).

== Other ways to do this in ONTAP

|===

h| To perform these tasks with... h| Refer to...

| The redesigned System Manager (available with ONTAP 9.7 and later) | link:https://docs.netapp.com/us-en/ontap/task_dp_prepare_mirror.html[Prepare for mirroring and vaulting^]
| The ONTAP command line interface | link:https://docs.netapp.com/us-en/ontap/peering/create-cluster-relationship-93-later-task.html[Create a cluster peer relationship (ONTAP 9.3 and later)^]

|===

// 2021-12-17, BURT 1446398
// 2022-1-24, remove unnecessary links
// 2022-1-27, change CLI link in table
